# Site Settings
lang: en
title: Bangalore Job Seekers Guide
tagline: Your Ultimate guide to job hunting in Bangalore
email: contact@imswarnil.com
description: Bangalore Job Seekers Guide is an open source project that aims to provide guidance and support to job seekers who are planning to move to Bangalore. Find your dream job in Bangalore with our step-by-step guide. Learn how to research the job market, network, and upskill for success. Perfect for fresher job seekers. Find your first job in Bangalore with our step-by-step guide.".
url: "https://bangalorejobseeker.imswarnil.com/"
permalink: /:categories/:title/
favicon: /img/Bangalore-Job-Seekers-Guide-white.png
gh_sponsor: imswarnil
hide_share_buttons: false
#theme_color: #eeeeee'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: G-RWV020VQE0

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
