# Site Settings
lang: en
title: Namaste Salesforce 
tagline: Say Namaste To Salesforce 
email: admin@namastesalesforce.com
description: Namaste Salesforce is a platform designed to help people upskill for jobs in the Salesforce ecosystem. As per reports, 1.1 billion jobs are expected to be created in India by 2022, and we want to empower people to take advantage of this growing opportunity. Our goal is to provide quality training and resources for anyone who wants to learn Salesforce and build a career in this field.
url: "https://salesforce.imswarnil.com"
permalink: /:categories/:title/
#favicon: /path/to/favicon.png
gh_sponsor: imswarnil
hide_share_buttons: false
#theme_color: '#eeeeee'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: G-RWV020VQE0

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
