# Site Settings
lang: en
title: Swarnil Teaches Salesforce
tagline: Learn Salesforce, Salesforce CRM Analytics & Salesforce UX Design From Swarnil
email: admin@namastesalesforce.com
description: Learn Salesforce along with me on Swarnil Teaches Salesforce! Access Salesforce tutorials, projects, notes, and resources on topics like Salesforce, CRM Analytics, and Salesforce UX design to grow your skills and start your journey today. Join my community and learn Salesforce with me. 
url: "https://salesforce.imswarnil.com"
permalink: /:categories/:title/
#favicon: /path/to/favicon.png
gh_sponsor: imswarnil
hide_share_buttons: false
#theme_color: '#eeeeee'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: G-RWV020VQE0

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
